#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<USAGE
Usage: $(basename "$0") [--template <path>] [--base <branch>] [--head <branch>]

Render PR body from template and print to stdout.
USAGE
}

ROOT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "${ROOT_DIR}" ]]; then
  echo "error: not inside git repository" >&2
  exit 1
fi

BASE_BRANCH="main"
HEAD_BRANCH="$(git -C "${ROOT_DIR}" rev-parse --abbrev-ref HEAD)"
TEMPLATE_PATH="${ROOT_DIR}/.github/pull_request_template.md"

while (($#)); do
  case "$1" in
    --template)
      TEMPLATE_PATH="$2"
      shift 2
      ;;
    --base)
      BASE_BRANCH="$2"
      shift 2
      ;;
    --head)
      HEAD_BRANCH="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ ! -f "${TEMPLATE_PATH}" ]]; then
  FALLBACK_TEMPLATE="${ROOT_DIR}/.github/PULL_REQUEST_TEMPLATE/pull_request_template_ja.md"
  if [[ -f "${FALLBACK_TEMPLATE}" ]]; then
    TEMPLATE_PATH="${FALLBACK_TEMPLATE}"
  else
    echo "error: template not found: ${TEMPLATE_PATH}" >&2
    exit 1
  fi
fi

render_template() {
  local template_file="$1"
  # Strip YAML front matter when template is from PULL_REQUEST_TEMPLATE/*.md
  awk '
    NR == 1 && $0 == "---" {in_front=1; next}
    in_front && $0 == "---" {in_front=0; next}
    !in_front {print}
  ' "${template_file}"
}

cat <<META
<!-- Generated by scripts/render_pr_body.sh -->
- Base: ${BASE_BRANCH}
- Head: ${HEAD_BRANCH}
- Generated: $(date '+%Y-%m-%d %H:%M:%S %z')

META

render_template "${TEMPLATE_PATH}"
